<?php

namespace Container9WGFz9m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTbProductsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.n8Ijc_L.App\Entity\TbProducts' shared service.
     *
     * @return \App\Entity\TbProducts
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.n8Ijc_L": it references class "App\\Entity\\TbProducts" but no such service exists.');
    }
}
