<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4BT6xHx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4BT6xHx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4BT6xHx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4BT6xHx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4BT6xHx\App_KernelDevDebugContainer([
    'container.build_hash' => '4BT6xHx',
    'container.build_id' => 'f9b36703',
    'container.build_time' => 1646031180,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4BT6xHx');
