<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPGz6x5j\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPGz6x5j/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPGz6x5j.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPGz6x5j\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPGz6x5j\App_KernelDevDebugContainer([
    'container.build_hash' => 'PGz6x5j',
    'container.build_id' => 'e6da1265',
    'container.build_time' => 1646126054,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPGz6x5j');
